---
apiVersion: v1
kind: Namespace
metadata:
  name: nodejs-dev-x1
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-logging: "true"
    openshift.io/cluster-monitoring: "true"
    argocd.argoproj.io/managed-by: "openshift-gitops"
---
apiVersion: v1
kind: Namespace
metadata:
  name: nodejs-dev-x1-staging
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-logging: "true"
    openshift.io/cluster-monitoring: "true"
    argocd.argoproj.io/managed-by: "openshift-gitops"
---
apiVersion: v1
kind: Namespace
metadata:
  name: nodejs-dev-x1-production
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-logging: "true"
    openshift.io/cluster-monitoring: "true"
    argocd.argoproj.io/managed-by: "openshift-gitops"
---
