apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: nodejs-dev-x1-staging

images:
- digest: sha256:9f51dcfdfbe9469e0ef30b5e34dc1f3815028e0aa465c5d765d497ce20b35653
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: quay-registry-quay-quay.apps.rosa.sb1237-rosa.b20c.p3.openshiftapps.com/skitamura-quay-org/nodejs-dev-x1/nodejs-dev-x1
